# Generated by Django 4.2.2 on 2023-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'Exempt'), (2, 'Active'), (3, 'Trailing'), (4, 'Canceled'), (5, 'Trial Expired')], db_index=True, default=3),
        ),
    ]
