# Generated by Django 4.2.2 on 2023-06-25 18:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='when',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 18, 11, 25, 248771, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
