# Generated by Django 4.2.2 on 2023-06-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_user_entry_when'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'entries', 'verbose_name_plural': 'entries'},
        ),
    ]
